Repository Classy-Potatoes/Front_Classy-Groupware, pull requests merged in 2023-12, with the labels that each got.

#27 Feat/#2/ 기본 네비 css 변경
  .env
  .idea/workspace.xml
  package-lock.json
  package.json
  src/App.js
  src/dashBoard/components/common/Navbar.js
  src/project/apis/sample.js
  src/project/components/common/ProjectNavBar.js
  src/style/Nav.css
Labels: HTML&CSS, Question

#28 대시보드 css 수정
  src/dashBoard/layouts/Layout.js
  src/style/Nav.css
Labels: HTML&CSS

#29 Feat/#19/로그인관련 로그인 기능 완료
  package-lock.json
  package.json
  public/member/loginBanner.png
  public/member/loginBannerLogo.png
  public/member/loginLogoWh.png
  public/member/login_pwd.png
  public/member/login_user.png
  src/App.js
  src/dashBoard/components/common/Navbar.js
  src/dashBoard/modules/index.js
  src/login/components/sample.js
  src/login/layouts/sample.js
  src/login/modules/sample.js
  src/login/pages/sample.js
  src/login/utils/sample.js
  src/member/apis/Api.js
  src/member/apis/MemberAPICalls.js
  src/member/components/form/LoginForm.js
  src/member/components/router/ProtectedRoute.js
  src/member/layouts/sample.js
  src/member/modules/MemberModule.js
  src/member/pages/Login.js
  src/member/utils/TokenUtils.js
  src/style/GlobalStyles.js
  src/style/calendar.css
  src/style/main.css
  src/style/member/styleTest.css
  src/style/nav.css
Labels: FE, Feature, HTML&CSS

#30 Feat/#19/로그인관련 로그인 기능 완료
  src/App.js
Labels: FE, Feature, HTML&CSS

#31 Feat/#19/로그인관련 로그인 기능 완료
  src/App.js
  src/common/apis/Api.js
  src/common/components/form/LoginForm.js
  src/common/components/router/ProtectedRoute.js
  src/common/modules/index.js
  src/common/pages/Login.js
  src/member/apis/MemberAPICalls.js
  src/member/components/router/test.js
  src/member/pages/test.js
  src/store.js
Labels: FE, Feature, HTML&CSS

#32 Feat/#19/로그인관련 로그인 기능 완료
  src/App.js
  src/common/components/router/ProtectedRoute.js
  src/common/pages/Login.js
  src/dashBoard/components/common/Navbar.js
Labels: Bug

#33 Feat/#19/로그인관련 네비바 버그수정
  src/style/nav.css
Labels: Bug

#34 Feature/#5/프로젝트메인페이지
  package-lock.json
  package.json
  src/App.js
  src/common/modules/index.js
  src/project/apis/ProjectAPICalls.js
  src/project/components/common/ProjectNavBar.js
  src/project/components/items/ProjectListItem.js
  src/project/components/modal/NewProjectWriteModal.js
  src/project/modules/ProjectModule.js
  src/project/modules/sample.js
  src/style/Project.css
Labels: FE

#35 Feat/#5/경로이름변경
  src/App.js
  src/dashBoard/components/common/Navbar.js
Labels: Fix

#41 feature/#17휴가신청서 완성
  src/appreval/apis/RegistDocumentAPICalls.js
  src/appreval/components/Form/Vacation.js
  src/appreval/components/mui/ApprovalDatePicker.js
  src/appreval/components/mui/VacationSelect.js
  src/appreval/modules/ApprovalModule.js
  src/style/approval/Vacation.css
Labels: FE, Feature

#42 Feat/#19/회원가입 구현 완료
  package-lock.json
  package.json
  src/common/components/form/LoginForm.js
  src/common/pages/Login.js
  src/member/apis/MemberAPICalls.js
  src/member/components/form/SearchIdForm.js
  src/member/components/form/SearchPwdForm.js
  src/member/components/form/SignupForm.js
  src/member/components/router/test.js
  src/member/modules/MemberModule.js
  src/member/pages/Signup.js
  src/member/utils/SignupInputChecks.js
  src/style/member/login.css
Labels: FE, Feature, HTML&CSS

#45 Feat/#20/ 마이페이지, 연락망, 회원관리 라우팅 설정
  src/App.js
  src/dashBoard/components/common/Header.js
  src/dashBoard/components/common/Navbar.js
  src/member/components/router/AdminPageNavBar.js
  src/member/components/router/MyPageNavBar.js
  src/member/layouts/AdminPageLayout.js
  src/member/layouts/MyPageLayout.js
  src/member/layouts/NetworkPageLayout.js
  src/member/layouts/sample.js
  src/member/pages/admin/MemberManagement.js
  src/member/pages/admin/NonMemberManagement.js
  src/member/pages/mypage/MemberReturn.js
  src/member/pages/mypage/PasswordChange.js
  src/member/pages/mypage/Profile.js
  src/member/pages/network/MemberNetwork.js
  src/style/main.css
  src/style/member/member.css
  src/style/nav.css
Labels: FE, HTML&CSS

#46 Feat/#6/프로젝트디테일, 대시보드
  src/App.js
  src/project/apis/ProjectAPICalls.js
  src/project/components/common/ProjectNavBar.js
  src/project/components/common/ProjectNavList.js
  src/project/components/common/ProjectRight.js
  src/project/components/items/MyProjectTaskListItem.js
  src/project/components/items/MyProjectTodoListItem.js
  src/project/components/items/ProjectInviteItem.js
  src/project/components/items/ProjectInvitedItem.js
  src/project/components/items/ProjectItem.js
  src/project/components/items/ProjectListItem.js
  src/project/components/lists/MyProjectTaskList.js
  src/project/components/lists/MyProjectTodoList.js
  src/project/components/modal/InviteModal.js
  src/project/components/modal/ProjectModifyModal.js
  src/project/layouts/ProjectDashBoard.js
  src/project/layouts/ProjectDetailLayout.js
  src/project/modules/ProjectModule.js
  src/project/pages/projects/MyDeptProjectMain.js
  src/project/pages/projects/MyProjectMain.js
  src/project/pages/projects/ProjectDetail.js
  src/project/pages/projects/ProjectInvite.js
  src/style/Project.css
  src/style/nav.css
  src/style/project/Project.css
Labels: FE, API

#48 Feat / #2 / calendar
  src/App.js
  src/calendar/layouts/CalendarLayout.js
Labels: FE, Fix

#50 Feat/#6/ 대시보드 네비
  package-lock.json
  package.json
  public/project/attem.png
  public/project/calender-icon2.png
  public/project/담당자.png
  public/project/요청.png
  public/project/우선순위.png
  src/project/apis/ProjectAPICalls.js
  src/project/apis/ProjectPostAPICalls.js
  src/project/apis/ProjectTaskAPICalls.js
  src/project/components/common/ProjectNavList.js
  src/project/components/items/MyProjectTaskListItem.js
  src/project/components/items/ProjectManagerItem.js
  src/project/components/lists/ProjectPostList.js
  src/project/components/modal/InviteModal.js
  src/project/layouts/ProjectDashBoard.js
  src/project/pages/projects/ProjectPostWrite.js
  src/project/pages/projects/ProjectTaskWrite.js
  src/style/GlobalStyles.js
  src/style/nav.css
  src/style/project/Project.css
Labels: FE, HTML&CSS

#51 Feat/#20/회원가입파트 중간머지
  package-lock.json
  package.json
  src/App.js
  src/dashBoard/components/common/PagingBar.js
  src/member/apis/MemberAPICalls.js
  src/member/components/form/SignupForm.js
  src/member/modules/MemberModule.js
  src/member/pages/admin/NonMemberManagement.js
  src/member/utils/SignupInputChecks.js
  src/style/member/admin.css
Labels: FE, Feature, HTML&CSS

#52 Feat/#20/회원가입파트
  src/App.js
  src/common/modules/index.js
  src/dashBoard/components/common/Navbar.js
  src/member/apis/AdminAPICalls.js
  src/member/apis/MemberAPICalls.js
  src/member/components/common/AdminMemberTop.js
  src/member/components/common/MemberPagingBar.js
  src/member/components/common/NonMemberTop.js
  src/member/components/form/MemberInfoRegistModal.js
  src/member/components/lists/AdminMemberList.js
  src/member/components/lists/NonMemberList.js
  src/member/components/router/AdminPageNavBar.js
  src/member/modules/AdminModule.js
  src/member/modules/MemberModule.js
  src/member/pages/admin/AdminMemberMain.js
  src/member/pages/admin/AdminMemberSearchMain.js
  src/member/pages/admin/MemberManagement.js
  src/member/pages/admin/NonMemberMain.js
  src/member/pages/admin/NonMemberManagement.js
  src/member/pages/admin/NonMemberSearchMain.js
  src/style/member/login.css
  src/style/member/member.css
Labels: FE, Feature, HTML&CSS

#54 Feat / #29 / project
  src/calendar/apis/CalendarAPICalls.js
  src/calendar/apis/SecondProjectAPICalls.js
  src/calendar/calendarStyle/Calendar.css
  src/calendar/components/CalendarMain.js
  src/calendar/layouts/CalendarLayout.js
  src/calendar/utils/MemberUtils.js
  src/calendar/utils/sample.js
  src/common/modules/index.js
  src/project/components/common/ProjectNavList.js
  src/project/components/items/MyProjectTodoListItem.js
  src/project/components/items/ProjectScheduleRegist.js
  src/project/components/items/ProjectScheduleReviews.js
  src/project/components/items/ProjectTodoRegist.js
  src/project/components/items/ProjectTodoReviews.js
  src/project/components/lists/ProjectScheduleList.js
  src/project/components/lists/ProjectTodoList.js
  src/project/components/modal/ProjectModifyModal.js
  src/project/modules/SecondProjectModule.js
  src/project/pages/projects/ProjectCalendarWrite.js
  src/project/pages/projects/ProjectTodoWrite.js
  src/style/project/Project.css
Labels: FE

#57 Feature/#7/프로젝트일반게시글
  public/project/board.png
  public/project/calendar.png
  public/project/invite.png
  public/project/search.png
  public/project/task.png
  public/project/todo.png
  src/common/modules/index.js
  src/member/utils/TokenUtils.js
  src/project/apis/ProjectPostAPICalls.js
  src/project/components/common/ProjectNavList.js
  src/project/components/items/ProjectItem.js
  src/project/components/items/ProjectPostItem.js
  src/project/components/items/ProjectPostReplyItem.js
  src/project/components/lists/MyProjectTaskList.js
  src/project/components/lists/ProjectPostList.js
  src/project/components/lists/ProjectPostReplyList.js
  src/project/components/modal/NewProjectWriteModal.js
  src/project/components/modal/ProjectModifyModal.js
  src/project/modules/ProjectModule.js
  src/project/modules/ProjectPostMedule.js
  src/project/pages/projects/ProjectPostWrite.js
  src/project/pages/projects/ProjectTaskWrite.js
  src/style/project/Project.css
Labels: FE, HTML&CSS

#59 Feat / #2 / calendar
  src/calendar/apis/SecondProjectAPICalls.js
  src/calendar/calendarStyle/Calendar.css
  src/calendar/images/checked.png
  src/calendar/layouts/CalendarLayout.js
  src/calendar/pages/CalendarNavbar.js
  src/project/components/common/ProjectNavList.js
  src/project/components/items/ProjectScheduleRegist.js
  src/project/components/items/ProjectTodoListItem.js
  src/project/components/items/ProjectTodoRegist.js
  src/project/components/lists/ProjectScheduleList.js
  src/project/components/lists/ProjectTodoList.js
  src/project/modules/SecondProjectModule.js
  src/project/pages/projects/ProjectCalendarWrite.js
  src/project/pages/projects/ProjectTodoWrite.js
Labels: FE

#66 Feat/#65/ 대시보드 조회
  public/project/Rectangle.png
  public/project/eva_arrow-left-fill.png
  src/App.js
  src/appreval/components/ReportLists/ReportWaiting.js
  src/dashBoard/components/common/Navbar.js
  src/dashBoard/components/item/DashBoardMyProjectTaskListItem.js
  src/dashBoard/components/item/DashBoardMyProjectTodoListItem.js
  src/dashBoard/components/item/DashBoardMyprojectItem.js
  src/dashBoard/components/list/DashBoardMyProjectTaskList.js
  src/dashBoard/components/list/DashBoardMyProjectTodoList.js
  src/dashBoard/components/list/DashBoardMyprojectList.js
  src/dashBoard/page/DashBoard.js
  src/dashBoard/page/DashBoardMyTask.js
  src/dashBoard/page/DashBoardMyTodo.js
  src/dashBoard/page/DashBoardMyproject.js
  src/project/apis/ProjectAPICalls.js
  src/project/apis/ProjectTaskAPICalls.js
  src/project/components/common/ProjectNavBar.js
  src/project/components/items/projectTask/ProjectTaskListItem.js
  src/project/components/modal/ProjectModifyModal.js
  src/project/modules/ProjectModule.js
  src/project/pages/projects/ProjectInvite.js
  src/project/pages/projects/ProjectPostWrite.js
  src/style/dashBoard/dashBoard.css
  src/style/main.css
  src/style/project/Project.css
Labels: FE, API

#67 Feat/#65/ 날씨 조회
  .env
  src/dashBoard/components/Weather/TodayWeather.js
  src/dashBoard/components/common/Navbar.js
  src/style/dashBoard/dashBoard.css
  src/style/nav.css
Labels: FE

#68 Feat/#65/ 결재함 조회
  src/dashBoard/components/item/DashBoardMyApprevalListItem.js
  src/dashBoard/components/list/DashBoardMyApprevalList.js
  src/dashBoard/page/DashBoard.js
  src/dashBoard/page/DashBoardMyAppreval.js
Labels: FE

#69 Feature/#3/쪽지작성
  package-lock.json
  package.json
  public/Vector.png
  public/note/fi-rs-comment.png
  public/note/fi-rs-paper-plane.png
  public/note/ic_outline-mail.png
  public/note/users.png
  src/App.js
  src/common/components/pagingBar/PagingBar.js
  src/common/modules/index.js
  src/note/apis/NoteAPICalls.js
  src/note/apis/sample.js
  src/note/components/common/NoteNavbar.js
  src/note/components/items/NoteItem.js
  src/note/components/items/NoteListItem.js
  src/note/components/items/NoteSearchSelectOption.js
  src/note/components/list/NoteList.js
  src/note/components/sample.js
  src/note/layouts/NoteLayout.js
  src/note/layouts/sample.js
  src/note/modules/NoteModule.js
  src/note/modules/sample.js
  src/note/pages/MemberListModal.js
  src/note/pages/NoteImportantMain.js
  src/note/pages/NoteReceived.js
  src/note/pages/NoteReceivedMain.js
  src/note/pages/NoteSave.js
  src/note/pages/NoteSearch.js
  src/note/pages/NoteSentMain.js
  src/note/pages/sample.js
  src/notice/pages/sample.js
  src/project/components/modal/NewProjectWriteModal.js
  src/style/member/login.css
  src/style/nav.css
  src/style/note/note.css
  src/style/pagingbar.css
Labels: FE, Feature, HTML&CSS

#71 Feat/#65/ 조회
  public/icon _Tools_.png
  src/App.js
  src/dashBoard/components/common/Navbar.js
  src/dashBoard/components/item/DashBoardMyApprevalListItem.js
  src/dashBoard/components/item/DashBoardMyNoteListItem.js
  src/dashBoard/components/item/DashBoardMyProjectTaskListItem.js
  src/dashBoard/components/list/DashBoardMyApprevalList.js
  src/dashBoard/components/list/DashBoardMyNoteList.js
  src/dashBoard/page/DashBoard.js
  src/dashBoard/page/DashBoardMyNote.js
  src/member/utils/TokenUtils.js
  src/project/apis/ProjectAPICalls.js
  src/project/components/common/ProjectNavBar.js
  src/project/components/modal/NewProjectWriteModal.js
  src/project/modules/ProjectModule.js
  src/project/pages/projects/ProjectInvite.js
  src/project/pages/projects/ProjectMyTask.js
  src/style/dashBoard/dashBoard.css
  src/style/nav.css
  src/style/project/Project.css
Labels: FE

#74 Feat/#65/ css수정
  src/project/components/items/projectPost/ProjectPostItem.js
  src/project/pages/projects/ProjectTaskWrite.js
  src/style/project/Project.css
Labels: HTML&CSS

#75 Feat / #72 / todo
  src/project/components/items/ProjectTodoRegist.js
  src/project/layouts/ProjectDashBoard.js
Labels: FE, Fix

#76 Feat/#65/ 업무담당자 수정
  src/project/components/items/projectTask/ProjectTaskListItem.js
Labels: FE

#77 Feat/ #72 / 할일 수정
  src/project/components/items/ProjectScheduleReviews.js
  src/project/components/items/projectPost/ProjectPostItem.js
  src/project/components/items/projectTask/ProjectTaskListItem.js
  src/project/layouts/ProjectDashBoard.js
  src/project/pages/projects/ProjectCalendarWrite.js
  src/project/pages/projects/ProjectTaskWrite.js
  src/project/pages/projects/ProjectTodoWrite.js
  src/style/project/Project.css
Labels: Bug, BE, API

#78 feature/#55/결재함,결재처리,참조보관함 완성
  src/App.js
  src/appreval/apis/ReportAPICalls.js
  src/appreval/apis/SignAPICalls.js
  src/appreval/components/ReportLists/ReferenceReport.js
  src/appreval/components/ReportLists/ReferenceReportSearch.js
  src/appreval/components/ReportLists/ReportApprove.js
  src/appreval/components/ReportLists/ReportApproveSearch.js
  src/appreval/components/ReportLists/ReportPaying.js
  src/appreval/components/ReportLists/ReportRecall.js
  src/appreval/components/ReportLists/ReportTurnback.js
  src/appreval/components/ReportLists/reportDetail/ReportVacationDetail.js
  src/appreval/components/ReportLists/reportDetail/ReprotExpenseDetail.js
  src/appreval/components/ReportLists/reportDetail/ReprotLetterDetail.js
  src/appreval/components/ReportLists/reportDetail/SelectDetailPage.js
  src/appreval/components/ReportLists/sign/SignApprove.js
  src/appreval/components/ReportLists/sign/SignApproveSearch.js
  src/appreval/components/ReportLists/sign/SignPaying.js
  src/appreval/components/ReportLists/sign/SignPayingSearch.js
  src/appreval/components/ReportLists/sign/SignTurnback.js
  src/appreval/components/ReportLists/sign/SignTurnbackSearch.js
  src/appreval/components/ReportLists/sign/SignWaiting.js
  src/appreval/components/ReportLists/sign/SignWaitingSearch.js
  src/appreval/components/common/ApprovalNavBar.js
  src/appreval/components/mui/SignUpCheckModal.js
  src/appreval/modules/ApprovalModule.js
  src/appreval/pages/ApprovalReport.js
  src/style/approval/Reprot.css
  src/style/approval/Sign.css
  src/style/approval/SignCheckModal.css
  src/style/approval/Vacation.css
Labels: FE, Feature, HTML&CSS

#79 Feat/#65/ 업무담당자 수정
  src/project/components/items/projectTask/ProjectTaskListItem.js
Labels: Bug, FE

#80 refactoring/전자결재/CSS수정/폴더명 수정
  src/App.js
  src/approval/apis/RegistDocumentAPICalls.js
  src/approval/apis/ReportAPICalls.js
  src/approval/apis/SignAPICalls.js
  src/approval/apis/approvalAPI.js
  src/approval/components/Form/Expense.js
  src/approval/components/Form/Letter.js
  src/approval/components/Form/Vacation.js
  src/approval/components/ReportLists/ReferenceReport.js
  src/approval/components/ReportLists/ReferenceReportSearch.js
  src/approval/components/ReportLists/ReportApprove.js
  src/approval/components/ReportLists/ReportApproveSearch.js
  src/approval/components/ReportLists/ReportPaying.js
  src/approval/components/ReportLists/ReportPayingSearch.js
  src/approval/components/ReportLists/ReportRecall.js
  src/approval/components/ReportLists/ReportRecallSearch.js
  src/approval/components/ReportLists/ReportTurnback.js
  src/approval/components/ReportLists/ReportTurnbackSearch.js
  src/approval/components/ReportLists/ReportWaiting.js
  src/approval/components/ReportLists/ReportWaitingSearch.js
  src/approval/components/ReportLists/reportDetail/ReportVacationDetail.js
  src/approval/components/ReportLists/reportDetail/ReprotExpenseDetail.js
  src/approval/components/ReportLists/reportDetail/ReprotLetterDetail.js
  src/approval/components/ReportLists/sign/SignApprove.js
  src/approval/components/ReportLists/sign/SignApproveSearch.js
  src/approval/components/ReportLists/sign/SignPaying.js
  src/approval/components/ReportLists/sign/SignPayingSearch.js
  src/approval/components/ReportLists/sign/SignTurnback.js
  src/approval/components/ReportLists/sign/SignTurnbackSearch.js
  src/approval/components/ReportLists/sign/SignWaiting.js
  src/approval/components/ReportLists/sign/SignWaitingSearch.js
  src/approval/components/common/ApprovalNavBar.js
  src/approval/components/common/ApprovalPagingBar.js
  src/approval/components/items/AllMember.js
  src/approval/components/mui/ApprovalDatePicker.js
  src/approval/components/mui/ReferenceLineModal.js
  src/approval/components/mui/ReprotDatePiker.js
  src/approval/components/mui/SignUpCheckModal.js
  src/approval/components/mui/VacationSelect.js
  src/approval/components/mui/approvalLineModal.js
  src/approval/components/tables/ReportWaitingTable.js
  src/approval/layouts/ApprovalLayOut.js
  src/approval/modules/ApprovalModule.js
  src/approval/utils/TokenUtils.js
  src/common/modules/index.js
  src/dashBoard/components/common/Navbar.js
  src/dashBoard/page/DashBoardMyAppreval.js
  src/note/components/items/NoteListItem.js
  src/style/nav.css
Labels: Refactor

#82 Feat/#65/ 오류수정
  src/project/components/items/projectPost/ProjectPostItem.js
  src/project/components/modal/ProjectModifyModal.js
  src/project/pages/projects/ProjectPostWrite.js
  src/style/project/Project.css
Labels: FE

#83 Feat/#3/쪽지쓰기
  package.json
  public/note/fi-rr-star.png
  public/note/trash-2.png
  src/App.js
  src/calendar/apis/CalendarAPICalls.js
  src/dashBoard/components/common/Navbar.js
  src/note/apis/NoteAPICalls.js
  src/note/components/common/NoteNavbar.js
  src/note/components/items/NoteItem.js
  src/note/components/items/NoteListItem.js
  src/note/components/items/NoteMemberListItem.js
  src/note/components/list/NoteList.js
  src/note/components/list/NoteMemberList.js
  src/note/modules/NoteModule.js
  src/note/pages/MemberListModal.js
  src/note/pages/NoteImportantMain.js
  src/note/pages/NoteReceived.js
  src/note/pages/NoteReceivedMain.js
  src/note/pages/NoteReplyModal.js
  src/note/pages/NoteSave.js
  src/note/pages/NoteSentMain.js
  src/note/utils/sample.js
  src/style/nav.css
  src/style/note/note.css
  src/style/note/noteSave.css
Labels: FE, Feature, API

#84 Feature/#10/쪽지읽기
  src/note/components/items/NoteListItem.js
Labels: FE, Feature, HTML&CSS

#85 feat/#10/쪽지 작성 링크 수정
  src/note/apis/NoteAPICalls.js
  src/note/components/items/NoteItem.js
  src/note/components/items/NoteListItem.js
  src/note/pages/MemberListModal.js
  src/style/note/note.css
  src/style/note/noteSave.css
Labels: FE, Feature, HTML&CSS, API

#87 feat/#10/쪽지 읽기-CSS 수정,검색 시 실시간 반영 수정
  src/note/apis/NoteAPICalls.js
  src/note/components/items/NoteItem.js
  src/note/components/items/NoteListItem.js
  src/note/modules/NoteModule.js
  src/note/pages/MemberListModal.js
  src/note/pages/NoteImportantMain.js
  src/note/pages/NoteReceivedMain.js
  src/note/pages/NoteReplyModal.js
  src/note/pages/NoteSentMain.js
  src/style/note/note.css
  src/style/note/noteSave.css
Labels: FE, Feature, HTML&CSS, API
